name: NextApp
description: NextApp is a mobile application produced by ERPCloud.systems Egyptian company.

publish_to: 'none' 

version: 2.1.1+33

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  intl: 
  google_fonts: ^4.0.4
  path_provider: ^2.1.0
  open_file: ^3.3.2
  dio: ^5.1.1 
  file_picker: ^5.3.2
  fluttertoast: ^8.0.9
  easy_localization: 
  shared_preferences: ^2.2.0
  dio_cookie_manager: ^2.0.0

  horizontal_data_table: ^4.1.5
  printing: ^5.10.4
  auto_size_text: ^3.0.0

  #permission_handler:
  permission_handler: ^10.4.3
  uuid: ^3.0.6
  curved_navigation_bar: ^1.0.3
  image_picker: ^0.8.7+5

  #GPS
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  geocoding: ^2.1.0
  maps_launcher: ^2.2.0
  flutter_map: 
  latlong2: 
  app_settings: 

  #Alert
  cool_alert: ^1.1.0
  quickalert: ^1.0.0
  lottie: ^1.4.0
  showcaseview: ^1.1.8
  share_plus: ^4.5.3
  url_launcher: ^6.1.6
  badges: ^2.0.3

  #Firebase
  firebase_messaging: ^14.6.3
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  cloud_firestore: ^4.2.0

  flutter_local_notifications: ^9.9.1
  upgrader: ^4.8.1
  package_info_plus: ^1.4.3+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.2.0
  bloc_concurrency: ^0.2.2
  flutter_screenutil: ^5.8.4
  syncfusion_flutter_charts: ^20.4.54
  expandable_menu: ^0.0.5
  flutter_native_splash: ^2.3.1
  dots_indicator: ^3.0.0
  timeago: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  flutter_barcode_scanner: ^2.0.0 
  colorful_safe_area: ^1.0.0
  flutter_pdfview: ^1.3.1

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0  
  # flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^2.0.1
 
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/nextApp.png"
  min_sdk_android: 21 

flutter_native_splash:
  image: assets/logo.png
  color: "#ffffff"

flutter:

  uses-material-design: true

  assets:
      - assets/
      - assets/logo.png
      - assets/hr.png
      - assets/locale/
      - assets/lottie/ 

dependency_overrides:
  package_info_plus: ^4.0.1
  wakelock_windows: any
  win32: any