name: next_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+7

environment:
  sdk: ">=2.15.0-110.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  intl: ^0.17.0
  flutter_barcode_scanner: ^2.0.0
  google_fonts: ^2.1.0
  path_provider: ^2.0.8
  open_file: ^3.2.1
  passwordfield: ^0.1.0
  http: ^0.13.3
  dio: ^4.0.0
  file_picker: ^4.3.0
  fluttertoast: ^8.0.9
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.0
  dio_cookie_manager: ^2.0.0

  #  infinite_scroll_pagination: ^3.1.0

  #  loadmore: ^2.0.1
  horizontal_data_table: ^4.1.2
  #  fwfh_text_style: ^2.7.3+1
  printing: ^5.7.1
  auto_size_text: ^3.0.0
  #permission_handler:
  permission_handler: ^10.2.0
  uuid: ^3.0.6
  curved_navigation_bar: ^1.0.3


#  flutter_widget_from_html_core:
#  flutter_html:
#  html: ^0.15.0
  image_picker: ^0.8.4+13
  scrollable_positioned_list: ^0.3.5
  #GPS
  geolocator: ^9.0.2
  trust_location: ^2.0.13
  google_maps_flutter: ^2.2.1
  geocoding: ^2.0.5
  maps_launcher: ^2.0.1
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  app_settings: ^4.1.8


  #Alert
  cool_alert: ^1.1.0
  quickalert: ^1.0.0
  awesome_snackbar_content: ^0.0.8
  flutter_beautiful_popup: ^1.7.0
  stylish_dialog: ^0.1.3
  emoji_alert: ^1.1.0
  #status_alert: ^1.0.0
  #notification alert
  edge_alert: ^0.0.1
  lottie: ^1.4.0
  showcaseview: ^1.1.8
  share_plus: ^4.5.3
  url_launcher: ^6.1.6
  badges: ^2.0.3
  getwidget: ^3.0.1

  #Firebase
  firebase_messaging: ^14.1.4
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  cloud_firestore: ^4.2.0

  flutter_local_notifications: ^9.9.1
  upgrader: ^4.8.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0  
  flutter_launcher_icons: "^0.11.0"
 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/classA_logo.png"
  min_sdk_android: 21 

# For information on the generic Dart part of this file, see the
# following page_models: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/logo.png
      - assets/hr.png
      - assets/locale/
      - assets/lottie/ 

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
