name: NextApp
description: NextApp is a mobile application produced by ERPCloud.systems Egyptian company.

publish_to: 'none' 

version: 1.0.2+10

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  intl: 
  google_fonts: ^6.2.1
  path_provider: ^2.1.0
  open_file: ^3.3.2
  dio: ^5.1.1 
  file_picker: ^8.0.6
  fluttertoast: ^8.0.9
  easy_localization: 
  shared_preferences: ^2.2.0
  dio_cookie_manager: ^3.1.1

  horizontal_data_table: ^4.1.5
  printing: ^5.10.4
  auto_size_text: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  dropdown_textfield: ^1.0.8
  flutter_gutter: ^2.1.1

  #permission_handler:
  permission_handler: ^11.0.1
  uuid: ^4.4.0
  curved_navigation_bar: ^1.0.3
  image_picker: ^1.1.2

  #GPS
  geolocator: ^12.0.0
  google_maps_flutter: ^2.2.1
  geocoding: ^3.0.0
  maps_launcher: ^2.2.0
  flutter_map: 
  latlong2: 
  app_settings: ^5.1.1

  #Alert
  cool_alert: ^2.0.1
  quickalert: ^1.0.0
  lottie: ^2.7.0
  showcaseview: ^3.0.0
  share_plus: ^10.0.0
  url_launcher: ^6.1.6
  badges: ^3.1.2

  #Firebase
  firebase_messaging: ^15.0.2
  firebase_core: ^3.1.1

  flutter_local_notifications: ^17.2.1
  upgrader: ^10.3.0
  package_info_plus: ^1.4.3+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.2.0
  bloc_concurrency: ^0.2.2
  flutter_screenutil: ^5.9.0
  syncfusion_flutter_charts: ^26.1.40
  expandable_menu: ^0.0.5
  flutter_native_splash: ^2.3.1
  dots_indicator: ^3.0.0
  timeago: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  flutter_barcode_scanner: ^2.0.0 
  colorful_safe_area: ^1.0.0
  flutter_pdfview: ^1.3.1
  change_app_package_name: ^1.3.0
  gif_view: ^0.4.4

dev_dependencies:
  dependency_validator: ^4.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
 
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  android_12:
    image: assets/logo.png


flutter:

  uses-material-design: true

  assets:
      - assets/
      - assets/logo.png
      - assets/hr.png
      - assets/locale/
      - assets/lottie/ 

dependency_overrides:
  package_info_plus: ^4.0.1
  wakelock_windows: any
  win32: any