name: NextApp
description: NextApp is a mobile application produced by ERPCloud.systems Egyptian company.

publish_to: 'none' 

version: 1.3.0+14

environment:
  sdk: ">=2.17.0-110.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  intl: ^0.17.0
  google_fonts: ^2.1.0
  path_provider: ^2.0.8
  open_file: ^3.2.1
  dio: ^5.1.1 
  file_picker: ^4.3.0
  fluttertoast: ^8.0.9
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.0
  dio_cookie_manager: ^2.0.0

  horizontal_data_table: ^4.1.5
  printing: ^5.7.1
  auto_size_text: ^3.0.0

  #permission_handler:
  permission_handler: ^10.2.0
  uuid: ^3.0.6
  curved_navigation_bar: ^1.0.3

  image_picker: ^0.8.4+13

  #GPS
  geolocator: ^9.0.2
  trust_location: ^2.0.13
  google_maps_flutter: ^2.2.1
  geocoding: ^2.0.5
  maps_launcher: ^2.0.1
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  app_settings: ^4.1.8

  #Alert
  cool_alert: ^1.1.0
  quickalert: ^1.0.0
  lottie: ^1.4.0
  showcaseview: ^1.1.8
  share_plus: ^4.5.3
  url_launcher: ^6.1.6
  badges: ^2.0.3

  #Firebase
  firebase_messaging: ^14.2.6
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  cloud_firestore: ^4.2.0

  flutter_local_notifications: ^9.9.1
  upgrader: ^4.8.1
  package_info_plus: ^1.4.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.2.0
  bloc_concurrency: ^0.2.1
  flutter_screenutil: ^5.6.1
  syncfusion_flutter_charts: ^20.4.54


dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0  
  flutter_launcher_icons: "^0.11.0"
 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/nextApp.png"
  min_sdk_android: 21 


flutter:

  uses-material-design: true

  assets:
      - assets/
      - assets/logo.png
      - assets/hr.png
      - assets/locale/
      - assets/lottie/ 