// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm3_r2PGRYdttl7O7BoTxn0Q9nTRMXIrs',
    appId: '1:554398885603:android:453cd0bacd8d962fcc07d6',
    messagingSenderId: '554398885603',
    projectId: 'nextapp-9fd93',
    storageBucket: 'nextapp-9fd93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk7byA1N7UOvbf1zya4NLumsRVtKlp2qI',
    appId: '1:554398885603:ios:6a9b77b82196c9ddcc07d6',
    messagingSenderId: '554398885603',
    projectId: 'nextapp-9fd93',
    storageBucket: 'nextapp-9fd93.appspot.com',
    androidClientId: '554398885603-daou0enrvftqb9scaplmja12eqt4ince.apps.googleusercontent.com',
    iosClientId: '554398885603-768g28pj1e9b4j24046a44jh9jal6sq9.apps.googleusercontent.com',
    iosBundleId: 'mobi.nextapp.nextapp',
  );
}
